### PR TITLE
Proposed initial README

### PR DESCRIPTION
**Pull request by rvagg**
Just containing a goal for the WG laid out as a series of points.

### CODE REVIEW

**Comment by bnoordhuis** [comment]
LGTM but can I suggest you wrap lines at 80 columns for easier reading on terminals?

**Comment by jasnell** [comment]
@rvagg ... can you rebase this?

**Comment by rvagg** [comment]
@jasnell can I abort on this and hand it over to you? I'm not sure how relevant this is now that we've evolved a little.

**Comment by jasnell** [comment]
:+1:

**Comment by jasnell** [comment]
Closing this. Will be replacing it soon

**Pull request closed without merging**
