### PR TITLE
Losslessly optimize schedule.png by zopflipng

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Size change: 117739 (114K) -> 95588 (93K), 81.186% of original.

### CODE REVIEW

**Comment by TheAlphaNerd** [comment]
Do we need to keep it at the current resolution as well? Would it be useful to keep the original in the repo too uncompressed but serve the compressed version in the readme?

**Comment by jasnell** [comment]
I'm good with this. I don't see much reason to keep the original. LGTM

**Comment by TheAlphaNerd** [comment]
kk... LGTM

**Comment by PeterDaveHello** [comment]
Resolutions of these two pics are the same, git repo has copy of the old one, so there is no need to keep them both, and it is totally compatible with origin file.

**Comment by TheAlphaNerd** [comment]
closing as we have a new image... please feel free to make a new PR

**Comment by PeterDaveHello** [comment]
why not just update it in the same pr?

**Pull request closed without merging**
