### PR TITLE
added proper lts chart, added note about 4.4.1 being an example

### PR DESCRIPTION
**Pull request by rvagg**

### CODE REVIEW

**Comment by thefourtheye** [comment]
The image is still attributed to nodesource?

**Comment by rvagg** [comment]
yes

**Comment by thefourtheye** [comment]
@rvagg I was thinking that we would be using "Node.js Foundation" everywhere. Where should we use Nodesource?

**Comment by rvagg** [comment]
this was designed by a NodeSource designer and is therefore (c) NodeSource, but it's licensed under creative commons

**Comment by thefourtheye** [comment]
Cool. LGTM.

**Pull request merged**
