### PR TITLE
doc: update the schedule

### PR DESCRIPTION
**Pull request by jasnell**
Update the LTS schedule to add v7 and v8 details.

### CODE REVIEW

**Comment by TheAlphaNerd** [comment]
@jasnell this needs to be rebased

**Comment by gibfahn** [comment]
@jasnell we should get this rebased and landed ASAP.

**Comment by mhdawson** [comment]
@jasnell pin, can you update this week or should Gibson or myself submit a new PR to get this landed ?

**Comment by jasnell** [comment]
I'll get an update in today

**Comment by gibfahn** [comment]
@jasnell The Node 8 EoL date will presumably be affected by https://github.com/nodejs/LTS/issues/186.

**Comment by jasnell** [comment]
@nodejs/lts ... schedule is updated, made a few other formatting tweaks and added an ICal with the schedule. PTAL

**Comment by gibfahn** [comment]
@nodejs/lts I'll land later today unless there are any objections (or someone beats me to it...).

**Comment by mohammadjnoor** [comment]
@jasnell

**Comment by mohammadjnoor** [comment]
@MylesBorins

**Comment by mohammadjnoor** [comment]
@MylesBorins

**Comment by mohammadjnoor** [comment]
@MylesBorins

**Comment by mohammadjnoor** [comment]
@

**Comment by mohammadjnoor** [comment]
> > > > @mohammadjnoor @jasnell @MylesBorins @gibfahn @mhdawson

**Review by rawmet1989 — APPROVED** [review]

**Pull request merged**
