### PR TITLE
doc: Add minutes for July 27 2016

### PR DESCRIPTION
**Pull request by mhdawson**

### CODE REVIEW

**Comment by TheAlphaNerd** [comment]
LGTM

**Comment by addaleax** [comment]
`June`? :P

**Comment by mhdawson** [comment]
good catch it was june, updated commit comment

**Comment by mhdawson** [comment]
Will land next week unless there are other comments before then

**Comment by mhdawson** [comment]
Landed as 3821a26bfe40ac3b25d1999fbfdaeaffce499e15

**Pull request closed without merging**
