### PR TITLE
doc: release schedule as JSON

### PR DESCRIPTION
**Pull request by rvagg**
Idea floated in #107 

The future dates for `"start"` and `"lts"` and future `"codename"` (for "v8" at this stage but we'd push that out to include `"v9"` when it's in sight) will be filled in when we have them, they should be considered placeholders at the moment (i.e. the actual date we release v8 is unknown but we know it'll be in April, same as the switch-to-LTS point).

@nodejs/lts

### CODE REVIEW

**Comment by fene** [comment]
this looks good! can we build an official website akin to http://github.com/fene/nver with it? i feel like it's fairly simple and makes sense

**Comment by rvagg** [comment]
the README here still feels like the right place for that since we link to it from so many places, and it'd be cool to still promote third-party sites if they do a better job too

**Comment by srl295** [comment]
Now i'll have to update [ICU's](http://icu-project.org/xml/icumeta.json)

**Comment by rvagg** [comment]
live

**Review by leem23m — APPROVED** [review]

**Pull request merged**
